# Generated by Django 5.0.7 on 2024-08-07 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='lists',
        ),
    ]
